[package]
name = "webdrop"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.0", features = ["multipart"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["fs"] }
