name: Node

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  check:
    name: Check web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm run lint

    - name: Check
      run: pnpm run check