name: Build server

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main', 'develop' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose
